export enum userLogActionTypes {
  GET_USER_FOODLOG = 'GET_USER_FOODLOG',
  ADD_FOOD_TO_LOG = 'ADD_FOOD_TO_LOG',
  GET_DAY_TOTALS = 'GET_DAY_TOTALS',
  CHANGE_SELECTED_DATE = 'CHANGE_SELECTED_DATE',
  SET_DAY_NOTES = 'SET_DAY_TOTALS',
  DELETE_FOOD_FROM_LOG = 'DELETE_FOOD_FROM_LOG',
  GET_USER_WEIGHT_LOG = 'GET_USER_WEIGHT_LOG',
  ADD_WEIGHT_LOG = 'ADD_WEIGHT_LOG',
  UPDATE_WEIGHT_LOG = 'UPDATE_WEIGHT_LOG',
  GET_USER_EXERCISES_LOG = 'GET_USER_EXERCISES_LOG',
  ADD_USER_EXERCISES_LOG = 'ADD_USER_EXERCISES_LOG',
  UPDATE_USER_EXERCISES_LOG = 'UPDATE_USER_EXERCISES_LOG',
}
